// Cytat dnia. Tłumaczenia własne; przy cytatach o spornym autorstwie zostawiamy tylko te z pewnym źródłem.
import { daysBetween, today } from './util.js';

export const QUOTES = [
  ['Jesteśmy tym, co wielokrotnie robimy. Doskonałość nie jest więc czynem, lecz nawykiem.', 'Will Durant, streszczając Arystotelesa'],
  ['Nie liczę brzuszków. Zaczynam liczyć dopiero, kiedy zaczyna boleć.', 'Muhammad Ali'],
  ['Nienawidziłem każdej minuty treningu, ale mówiłem sobie: nie odpuszczaj. Pocierp teraz i resztę życia przeżyj jako mistrz.', 'Muhammad Ali'],
  ['Mistrzów nie robi się na siłowniach. Mistrzów robi się z czegoś, co mają w środku: pragnienia, marzenia, wizji.', 'Muhammad Ali'],
  ['Nie licz dni. Spraw, żeby dni się liczyły.', 'Muhammad Ali'],
  ['Pierwszym i najlepszym zwycięstwem jest pokonanie samego siebie.', 'Platon'],
  ['Nie chodzi o to, czy zostaniesz powalony. Chodzi o to, czy wstaniesz.', 'Vince Lombardi'],
  ['Zmęczenie robi z nas wszystkich tchórzy.', 'Vince Lombardi'],
  ['Praktyka nie czyni mistrzem. Mistrzem czyni tylko doskonała praktyka.', 'Vince Lombardi'],
  ['Zwycięzcy nigdy się nie poddają, a ci, którzy się poddają, nigdy nie wygrywają.', 'Vince Lombardi'],
  ['Różnica między człowiekiem sukcesu a innymi to nie brak siły ani wiedzy, tylko brak woli.', 'Vince Lombardi'],
  ['Sukces to suma drobnych wysiłków powtarzanych dzień po dniu.', 'Robert Collier'],
  ['Dyscyplina to most między celami a osiągnięciami.', 'Jim Rohn'],
  ['Albo ty rządzisz dniem, albo dzień rządzi tobą.', 'Jim Rohn'],
  ['Dbaj o swoje ciało. To jedyne miejsce, w którym musisz mieszkać.', 'Jim Rohn'],
  ['Ludzie mówią, że motywacja nie trwa długo. Kąpiel też nie, dlatego zaleca się ją codziennie.', 'Zig Ziglar'],
  ['Trudności wzmacniają umysł tak, jak praca wzmacnia ciało.', 'Seneka'],
  ['Nie dlatego nie mamy odwagi, że rzeczy są trudne. Są trudne, bo nie mamy odwagi.', 'Seneka'],
  ['Nie jest tak, że mamy mało czasu. Tylko dużo go marnujemy.', 'Seneka'],
  ['Kto nie wie, do którego portu płynie, dla tego żaden wiatr nie jest pomyślny.', 'Seneka'],
  ['Częściej cierpimy w wyobraźni niż w rzeczywistości.', 'Seneka'],
  ['To, co stoi na drodze, staje się drogą.', 'Marek Aureliusz'],
  ['Nie trać czasu na rozważania, jaki powinien być dobry człowiek. Bądź nim.', 'Marek Aureliusz'],
  ['Rano, kiedy ciężko ci wstać, pomyśl: budzę się do pracy człowieka.', 'Marek Aureliusz'],
  ['Masz władzę nad swoim umysłem, nie nad wydarzeniami. Zrozum to, a znajdziesz siłę.', 'Marek Aureliusz'],
  ['Nic wielkiego nie powstaje nagle.', 'Epiktet'],
  ['Jak długo jeszcze będziesz zwlekał, zanim zaczniesz wymagać od siebie tego, co najlepsze?', 'Epiktet'],
  ['Najpierw powiedz sobie, kim chcesz być. Potem rób to, co musisz.', 'Epiktet'],
  ['Nie niepokoją nas rzeczy, lecz nasze mniemania o rzeczach.', 'Epiktet'],
  ['Przypadek sprzyja przygotowanym umysłom.', 'Louis Pasteur'],
  ['Ostatnie trzy, cztery powtórzenia to te, które budują mięsień.', 'Arnold Schwarzenegger'],
  ['Siła nie bierze się z wygrywania. Buduje ją to, z czym się zmagasz.', 'Arnold Schwarzenegger'],
  ['Umysł jest granicą. Jeśli umysł potrafi coś sobie wyobrazić i w to uwierzyć, możesz to osiągnąć.', 'Arnold Schwarzenegger'],
  ['Każdy chce być kulturystą, ale nikt nie chce dźwigać ciężkich ciężarów.', 'Ronnie Coleman'],
  ['Nie boję się człowieka, który raz przećwiczył 10 000 kopnięć. Boję się tego, który jedno kopnięcie przećwiczył 10 000 razy.', 'Bruce Lee'],
  ['Nie ma granic. Są tylko płaskowyże, a na nich nie wolno ci zostać.', 'Bruce Lee'],
  ['Wiedza nie wystarczy, trzeba ją stosować. Chęć nie wystarczy, trzeba działać.', 'Johann Wolfgang von Goethe'],
  ['Nie trafiłem ponad 9000 rzutów w karierze. Wiele razy przegrałem. I właśnie dlatego odnoszę sukcesy.', 'Michael Jordan'],
  ['Jedni chcą, żeby to się stało. Inni marzą, żeby to się stało. A jeszcze inni sprawiają, że to się dzieje.', 'Michael Jordan'],
  ['Nie trafiasz w sto procent strzałów, których nie oddajesz.', 'Wayne Gretzky'],
  ['Geniusz to jeden procent natchnienia i dziewięćdziesiąt dziewięć procent potu.', 'Thomas Edison'],
  ['Nie poniosłem porażki. Znalazłem 10 000 sposobów, które nie działają.', 'Thomas Edison'],
  ['Rób, co możesz, tym, co masz, tam, gdzie jesteś.', 'Theodore Roosevelt'],
  ['Chwała należy do tego, kto naprawdę jest na arenie, z twarzą umazaną kurzem, potem i krwią.', 'Theodore Roosevelt'],
  ['Czy myślisz, że potrafisz, czy że nie potrafisz, masz rację.', 'Henry Ford'],
  ['Co mnie nie zabije, to mnie wzmocni.', 'Friedrich Nietzsche'],
  ['Kto ma po co żyć, zniesie prawie każde jak.', 'Friedrich Nietzsche'],
  ['Dyscyplina równa się wolność.', 'Jocko Willink'],
  ['Kiedy myślisz, że już nie dasz rady, jesteś dopiero na 40% swoich możliwości.', 'David Goggins'],
  ['Sekretem posuwania się naprzód jest zacząć.', 'Mark Twain'],
  ['Podróż tysiąca mil zaczyna się od pierwszego kroku.', 'Laozi'],
  ['Nie chodzi o to, jak mocno uderzasz. Chodzi o to, jak mocno możesz oberwać i dalej iść do przodu.', 'Rocky Balboa, film z 2006'],
  ['Każdy ma plan, dopóki nie dostanie w szczękę.', 'Mike Tyson'],
  ['Dyscyplina to robienie tego, czego nienawidzisz, tak jakbyś to kochał.', 'Mike Tyson'],
  ['Trenowałem cztery lata, żeby biec dziewięć sekund.', 'Usain Bolt'],
  ['Sukces nie jest przypadkiem. To ciężka praca, wytrwałość, nauka i poświęcenie.', 'Pelé'],
  ['Jedyne miejsce, gdzie sukces przychodzi przed pracą, to słownik.', 'Vidal Sassoon'],
  ['Sukces nie polega na wielkości. Polega na konsekwencji. Konsekwentna ciężka praca prowadzi do sukcesu.', 'Dwayne Johnson'],
  ['Wstyd zestarzeć się, nie zobaczywszy piękna i siły, do jakich zdolne jest twoje ciało.', 'Sokrates, według Ksenofonta'],
  ['Nie odkładaj do jutra tego, co możesz zrobić dziś.', 'Benjamin Franklin'],
  ['Energia i wytrwałość pokonują wszystko.', 'Benjamin Franklin'],
  ['Nic na świecie nie zastąpi wytrwałości.', 'Calvin Coolidge'],
  ['Żeby zacząć, przestań mówić i zacznij działać.', 'Walt Disney'],
  ['Dać z siebie mniej niż wszystko to zmarnować dar.', 'Steve Prefontaine'],
  ['Tylko zdyscyplinowani są w życiu wolni.', 'Eliud Kipchoge'],
  ['Żaden człowiek nie jest ograniczony.', 'Eliud Kipchoge'],
  ['Nie stawiaj granic niczemu. Im więcej marzysz, tym dalej zajdziesz.', 'Michael Phelps'],
  ['Kropla drąży skałę nie siłą, lecz częstym padaniem.', 'Owidiusz'],
  ['Kto cierpi, zanim musi, cierpi więcej, niż musi.', 'Seneka'],
  ['Nie pozwól, żeby to, czego nie potrafisz, przeszkadzało ci w tym, co potrafisz.', 'John Wooden'],
  ['Sukces to spokój ducha, który przychodzi, gdy wiesz, że dałeś z siebie wszystko.', 'John Wooden'],
  ['Trudno pokonać kogoś, kto nigdy się nie poddaje.', 'Babe Ruth'],
  ['Mistrz to ktoś, kto wstaje, kiedy już nie może.', 'Jack Dempsey'],
  ['Życie jest jak jazda na rowerze. Żeby utrzymać równowagę, musisz jechać naprzód.', 'Albert Einstein'],
  ['Jeśli nie możesz latać, biegnij. Jeśli nie możesz biec, idź. Jeśli nie możesz iść, czołgaj się. Ale cokolwiek robisz, posuwaj się naprzód.', 'Martin Luther King'],
  ['Być zwyciężonym i nie ulec to zwycięstwo. Zwyciężyć i spocząć na laurach to klęska.', 'Józef Piłsudski'],
  ['Musicie od siebie wymagać, nawet gdyby inni od was nie wymagali.', 'Jan Paweł II'],
  ['Nie jestem utalentowany. Mam obsesję.', 'Conor McGregor'],
  ['Kto nie ma odwagi ryzykować, niczego w życiu nie osiągnie.', 'Muhammad Ali'],
  ['Niemożliwe to nie fakt. To opinia.', 'Muhammad Ali'],
  ['Kto nie znajdzie czasu na ruch, będzie musiał znaleźć czas na chorobę.', 'Edward Stanley, hrabia Derby'],
  ['Wszystko, co negatywne, presja i wyzwania, to dla mnie okazja, żeby się wznieść.', 'Kobe Bryant'],
  ['Wielkie rzeczy biorą się z ciężkiej pracy i wytrwałości. Bez wymówek.', 'Kobe Bryant'],
  ['Wolę spróbować i przegrać, niż nie spróbować wcale.', 'Michael Jordan'],
  ['Wytrwałość jest dla charakteru tym, czym węgiel dla stali.', 'Napoleon Hill'],
  ['Motywacja sprawia, że zaczynasz. Nawyk sprawia, że nie przestajesz.', 'Jim Ryun'],
  ['Najtrudniejszy ciężar na siłowni to drzwi wejściowe.', 'powiedzenie z siłowni'],
  ['Kto chce, szuka sposobu. Kto nie chce, szuka powodu.', 'przysłowie'],
  ['Bez pracy nie ma kołaczy.', 'przysłowie polskie'],
  ['Nie od razu Kraków zbudowano.', 'przysłowie polskie'],
];

const gcd = (a, b) => (b ? gcd(b, a % b) : a);

/** Każdy dzień inny cytat; krok 37 rozrzuca autorów, żeby dwa dni z rzędu nie mówił ten sam. */
export function quoteOfDay(day = today()) {
  const n = daysBetween('2026-01-01', day);
  const len = QUOTES.length;
  let step = 37;
  while (gcd(step, len) !== 1) step++;
  const i = ((n * step) % len + len) % len;
  const [text, author] = QUOTES[i];
  return { text, author };
}
